EventBundle_default:
    resource: "routing/default.yml"

EventBundle_event:
    resource: "routing/event.yml"
    prefix: /event

EventBundle_event_annotation:
    resource: "@EventBundle/Controller"
    prefix: /event
    type: annotation
